#!/bin/sh

set -e

mkdir -p /root/.ssh
mkdir -p /var/run/sshd
chmod 0755 /var/run/sshd
/usr/sbin/sshd

sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/g' /etc/ssh/sshd_config
sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/g' /etc/ssh/sshd_config


while true
do
 sleep 10000
done
