#!/bin/sh

set -e

mkdir -p /root/.ssh
mkdir -p /var/run/sshd
chmod 0755 /var/run/sshd
/usr/sbin/sshd

sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/g' /etc/ssh/sshd_config
sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/g' /etc/ssh/sshd_config


service ssh restart

cp /launch_traceroute.sh /root/launch_traceroute.sh

while true
do

  # echo "" > /root/mac_addresses
  # for i in `seq 100`;do
  #   ip route add default via $i.0.199.1 | true
  #   ping $i.0.199.1 -c 1 -t 1 > /dev/null 2>&1 | true
  #   echo `ip n | grep $i.0.199.1 | tr -s " " | cut -f 5 -d ' '` >>  /root/mac_addresses
  #   ip route del default via $i.0.199.1 | true
  # done
  #
  sleep 60

done
