#!/bin/sh

set -e

mkdir -p /root/.ssh
mkdir -p /var/run/sshd
chmod 0755 /var/run/sshd
/usr/sbin/sshd

sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/g' /etc/ssh/sshd_config
sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/g' /etc/ssh/sshd_config


service ssh restart

cp /launch_traceroute.sh /root/launch_traceroute.sh

tail -f /dev/null # To keep the container running forever
