#!/bin/sh

set -e

chown -R frr:frr /etc/frr
/etc/init.d/frr start

sed -i 's/#PasswordAuthentication yes/PasswordAuthentication no/g' /etc/ssh/sshd_config

mkdir -p /var/run/sshd
chmod 0755 /var/run/sshd
/usr/sbin/sshd

mkdir -p /root/.ssh

while true
do
  duration=$(shuf -i300-900 -n1)

  for i in {0..$duration..30}; do
    date "+%FT%T" > /home/looking_glass.txt
    vtysh -c 'show ip bgp' >> /home/looking_glass.txt
    sleep 30
  done

  # save router config
  vtysh -c 'write'

done
